app:
  name: 'dagger-pac-sample'
  version: '1.2.0'

log:
  level: 'debug'
  rollbar_env: 'dagger-pac-sample'

database:
  type: mysql
  host: localhost
  pool_max: 16
  port: 3306
  name: dagger_pac_sample
  location: Asia/Seoul
  # embedded in k8s secrets
  user: root
  pass: password
